version: "3.8"

services:
  dynamic_relay:
    image:  
    networks:
      vpn_network:
        ipv4_address: 189.20.0.51
    cap_add:
      - NET_ADMIN  # Required for route commands
    post_start:
      - command: ip route add 10.13.13.0/24 via 189.20.0.2
        user: root
    restart: unless-stopped
    env_file: dynamic_relay.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  stalechecker:
    image: tiarhax/michilante_stale_checker:latest
    networks:
      vpn_network:
        ipv4_address: 189.20.0.52
    restart: unless-stopped
    env_file: stalechecker.env
    depends_on:
      - dynamic_relay
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
      
  user_api:
    image: tiarhax/michilante_user_api:latest
    networks:
      vpn_network:
        ipv4_address: 189.20.0.53
    restart: unless-stopped
    env_file: user_api.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pinger:
    image: tiarhax/michilante_pinger
    networks:
      vpn_network:
        ipv4_address: 189.20.0.54
    restart: unless-stopped
    env_file: pinger.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  vpn_network:
    external: true
