version: "3.8"

services:
  dynamic_relay:
    image: tiarhax/michilante_dynamic_rtsp_relay:latest
    networks:
      vpn-bridge:
        ipv4_address: 10.13.13.151
    restart: unless-stopped
    env_file: dynamic_relay.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  stalechecker:
    image: tiarhax/michilante_stale_checker:latest
    networks:
      vpn-bridge:
        ipv4_address: 10.13.13.151
    restart: unless-stopped
    env_file: stalechecker.env
    depends_on:
      - dynamic_relay
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
      
  user_api:
    image: tiarhax/michilante_user_api:latest
    networks:
      vpn-bridge:
        ipv4_address: 10.13.13.151
    restart: unless-stopped
    env_file: user_api.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pinger:
    image: tiarhax/michilante_pinger
    networks:
      vpn-bridge:
        ipv4_address: 10.13.13.151
    restart: unless-stopped
    env_file: pinger.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  vpn-bridge:
    external: true
